/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.kelvin.projeto.apresentacao;

import java.beans.PropertyVetoException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author KELVIN
 */
public class InicioForm extends javax.swing.JFrame {
    
    private PesquisarAparelhosForm pesquisarAparelhosForm;
    private PesquisarAtletasForm pesquisarAtletasForm;
    private PesquisarAvaliacoesForm pesquisarAvaliacoesForm;
    private PesquisarMensalidadesForm pesquisarMensalidadesForm;
    private PesquisarPersonalTrainersForm pesquisarPersonalTrainersForm;
    private PesquisarTreinosForm pesquisarTreinosForm;
    /**
     * Creates new form InicioForm
     */
    public InicioForm() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesktop = new javax.swing.JDesktopPane();
        lblBackground = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        mnuPessoas = new javax.swing.JMenu();
        itmAtletas = new javax.swing.JMenuItem();
        itmPersonal = new javax.swing.JMenuItem();
        mnuAparelhos = new javax.swing.JMenu();
        itmAparelhos = new javax.swing.JMenuItem();
        mnuTreinos = new javax.swing.JMenu();
        itmPesquisarTreinos = new javax.swing.JMenuItem();
        mnuAvaliacoes = new javax.swing.JMenu();
        itmPesquisarAvaliacoes = new javax.swing.JMenuItem();
        mnuFinancas = new javax.swing.JMenu();
        itmMensalidades = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisAcademia");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/background.fw.png"))); // NOI18N

        pnlDesktop.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlDesktopLayout = new javax.swing.GroupLayout(pnlDesktop);
        pnlDesktop.setLayout(pnlDesktopLayout);
        pnlDesktopLayout.setHorizontalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1412, Short.MAX_VALUE)
        );
        pnlDesktopLayout.setVerticalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDesktopLayout.createSequentialGroup()
                .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPrincipal.setPreferredSize(new java.awt.Dimension(304, 40));

        mnuPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/gym16.png"))); // NOI18N
        mnuPessoas.setText("Pessoas");
        mnuPessoas.setMaximumSize(new java.awt.Dimension(100, 32767));

        itmAtletas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        itmAtletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/gymnast35.png"))); // NOI18N
        itmAtletas.setText("Atleta");
        itmAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAtletasActionPerformed(evt);
            }
        });
        mnuPessoas.add(itmAtletas);

        itmPersonal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itmPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/jump11.png"))); // NOI18N
        itmPersonal.setText("Personal Trainer");
        itmPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPersonalActionPerformed(evt);
            }
        });
        mnuPessoas.add(itmPersonal);

        menuPrincipal.add(mnuPessoas);

        mnuAparelhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/bicycle14.png"))); // NOI18N
        mnuAparelhos.setText("Aparelhos");
        mnuAparelhos.setMaximumSize(new java.awt.Dimension(102, 32767));

        itmAparelhos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        itmAparelhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/bicycle14.png"))); // NOI18N
        itmAparelhos.setText("Pesquisar Aparelhos");
        itmAparelhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAparelhosActionPerformed(evt);
            }
        });
        mnuAparelhos.add(itmAparelhos);

        menuPrincipal.add(mnuAparelhos);

        mnuTreinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/flexions.png"))); // NOI18N
        mnuTreinos.setText("Treinos");
        mnuTreinos.setMaximumSize(new java.awt.Dimension(100, 32767));

        itmPesquisarTreinos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        itmPesquisarTreinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/gym7.png"))); // NOI18N
        itmPesquisarTreinos.setText("Pesquisar Treinos");
        itmPesquisarTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPesquisarTreinosActionPerformed(evt);
            }
        });
        mnuTreinos.add(itmPesquisarTreinos);

        menuPrincipal.add(mnuTreinos);

        mnuAvaliacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/medical14.png"))); // NOI18N
        mnuAvaliacoes.setText("Avaliações");
        mnuAvaliacoes.setPreferredSize(new java.awt.Dimension(107, 32));

        itmPesquisarAvaliacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        itmPesquisarAvaliacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/gym5.png"))); // NOI18N
        itmPesquisarAvaliacoes.setText("Pesquisar Avaliações");
        itmPesquisarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPesquisarAvaliacoesActionPerformed(evt);
            }
        });
        mnuAvaliacoes.add(itmPesquisarAvaliacoes);

        menuPrincipal.add(mnuAvaliacoes);

        mnuFinancas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/creditcard3.png"))); // NOI18N
        mnuFinancas.setText("Finanças");
        mnuFinancas.setMaximumSize(new java.awt.Dimension(100, 32767));

        itmMensalidades.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        itmMensalidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/cash3.png"))); // NOI18N
        itmMensalidades.setText("Mensalidades");
        itmMensalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMensalidadesActionPerformed(evt);
            }
        });
        mnuFinancas.add(itmMensalidades);

        menuPrincipal.add(mnuFinancas);

        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/kelvin/projeto/apresentacao/Imagens/exit17.png"))); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.setMaximumSize(new java.awt.Dimension(100, 32767));
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        menuPrincipal.add(mnuSair);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAtletasActionPerformed
        try {                                           
            if(pesquisarAtletasForm == null){
                pesquisarAtletasForm = new PesquisarAtletasForm();
            }else{
                pnlDesktop.remove(pesquisarAtletasForm);
            }
            pesquisarAtletasForm.setVisible(true);    
            pnlDesktop.add(pesquisarAtletasForm);
            pesquisarAtletasForm.toFront();
            try {
                pesquisarAtletasForm.setMaximum(true);     
            } catch (PropertyVetoException ex) {
            
            }         
        }catch (SQLException ex) {     
        
        }
       
    }//GEN-LAST:event_itmAtletasActionPerformed

    private void itmPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPersonalActionPerformed
        try {          
            if(pesquisarPersonalTrainersForm == null){
                pesquisarPersonalTrainersForm = new PesquisarPersonalTrainersForm(); 
            }else{
                pnlDesktop.remove(pesquisarPersonalTrainersForm);
            }
            pesquisarPersonalTrainersForm.setVisible(true);
            pnlDesktop.add(pesquisarPersonalTrainersForm);
            pesquisarPersonalTrainersForm.toFront();
            try {
                pesquisarPersonalTrainersForm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                
            }            
        } catch (SQLException ex) {
 
        }                 
    }//GEN-LAST:event_itmPersonalActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void itmPesquisarTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPesquisarTreinosActionPerformed
        try {                                                    
            if(pesquisarTreinosForm == null){
                pesquisarTreinosForm = new PesquisarTreinosForm();
            }else{
                pnlDesktop.remove(pesquisarTreinosForm);
            }
            pnlDesktop.add(pesquisarTreinosForm);
            pesquisarTreinosForm.setVisible(true);
            pesquisarTreinosForm.toFront();
            try {
                pesquisarTreinosForm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                
            }           
        } catch (SQLException ex) {
                     
        }       
    }//GEN-LAST:event_itmPesquisarTreinosActionPerformed

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        JOptionPane.showMessageDialog(this, "SisAcademia será encerrado.");
        System.exit(0);
    }//GEN-LAST:event_mnuSairMouseClicked

    private void itmPesquisarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPesquisarAvaliacoesActionPerformed
        try { 
            if(pesquisarAvaliacoesForm == null){
               pesquisarAvaliacoesForm = new PesquisarAvaliacoesForm();
            }else{
                pnlDesktop.remove(pesquisarAvaliacoesForm);
            }
            pnlDesktop.add(pesquisarAvaliacoesForm);
            pesquisarAvaliacoesForm.setVisible(true);
            pesquisarAvaliacoesForm.toFront();
            try {
                pesquisarAvaliacoesForm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                
            }          
        } catch (SQLException ex) {
            
        }  
    }//GEN-LAST:event_itmPesquisarAvaliacoesActionPerformed

    private void itmAparelhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAparelhosActionPerformed
        try {   
            if(pesquisarAparelhosForm == null){
                pesquisarAparelhosForm = new PesquisarAparelhosForm();
            }else{
                pnlDesktop.remove(pesquisarAparelhosForm);
            }
            pnlDesktop.add(pesquisarAparelhosForm);
            pesquisarAparelhosForm.setVisible(true);
            pesquisarAparelhosForm.toFront();
            try {
                pesquisarAparelhosForm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                
            }
        }catch (SQLException ex) {
                
        }
    }//GEN-LAST:event_itmAparelhosActionPerformed

    private void itmMensalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMensalidadesActionPerformed
        try { 
            if(pesquisarMensalidadesForm == null){
                pesquisarMensalidadesForm = new PesquisarMensalidadesForm();
            }else{
                pnlDesktop.remove(pesquisarMensalidadesForm);
            }
            pnlDesktop.add(pesquisarMensalidadesForm);
            pesquisarMensalidadesForm.setVisible(true);
            pesquisarMensalidadesForm.toFront();
            try {
                pesquisarMensalidadesForm.setMaximum(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(null, "erro 1");
            }           
        } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "erro 2");     
        }     
    }//GEN-LAST:event_itmMensalidadesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAparelhos;
    private javax.swing.JMenuItem itmAtletas;
    private javax.swing.JMenuItem itmMensalidades;
    private javax.swing.JMenuItem itmPersonal;
    private javax.swing.JMenuItem itmPesquisarAvaliacoes;
    private javax.swing.JMenuItem itmPesquisarTreinos;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu mnuAparelhos;
    private javax.swing.JMenu mnuAvaliacoes;
    private javax.swing.JMenu mnuFinancas;
    private javax.swing.JMenu mnuPessoas;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenu mnuTreinos;
    private javax.swing.JDesktopPane pnlDesktop;
    // End of variables declaration//GEN-END:variables
}
